### ISSUE TITLE
send file with file_id

### ISSUE THREAD

**Issue by farbodmahini** [zelenin/telegram-bot-api#10]
when i want to send a document with url or link , i use this code : 

$client -> sendDocument(array('chat_id' => $chatid, 'document' => fopen($link, 'r')));

But now i want to know , How i can send file with file_id ? for Ex : BQADBAAD7QIAAoFEJAXq2UtTclEUhQI

i test this code : 
$client -> sendDocument(array('chat_id' => $chatid, 'document' => 'BQADBAAD7QIAAoFEJAXq2UtTclEUhQI'));

but's not working ! 
plz help me !
Thanks

**Comment by zelenin** [comment]
It's not library issue.
