### ISSUE TITLE
keboard markup help 

### ISSUE THREAD

**Issue by moein-rahimi** [zelenin/telegram-bot-api#12]
hi
first I want to thank for this nice library.
for my bot i need to make keyboard markup but i'm not sure how to do it.
I tried this but it didn't work:
````
$keyboard = array(
    'keyboard' => array(
        array("A", "B")
    )
);
$client->sendMessage(array('chat_id' => $chatid, 'text' => 'test', 'reply_markup' => $keyboard));
````

**Comment by zelenin** [comment]
You should use ReplyMarkup 

https://github.com/zelenin/telegram-bot-api/blob/master/Api.php#L89
https://github.com/zelenin/telegram-bot-api/blob/master/Type/ReplyKeyboardMarkup.php#L5

**Comment by moein-rahimi** [comment]
an example would be awesome, I saw the classes before but i'm not quite sure how to do it

**Comment by zelenin** [comment]
```php
$showKeyboard = new ReplyKeyboardMarkup();
$showKeyboard->keyboard = [
    ['bash.im', 'ithappens.me'],
    ['zadolba.li', 'anekdot.ru']
];
$showKeyboard->one_time_keyboard = false;
        
                        $response = $client->sendMessage([
                            'chat_id' => $update->message->from->id,
                            'text' => 'Выберите сайт:',
                            'reply_markup' => $showKeyboard,
                            'disable_web_page_preview' => true
                        ]);
```

**Comment by moein-rahimi** [comment]
hi thanks for your great reply, just there is a problem, the text message looks like is in a loop, the message sends like forever, it won't stop. 
it should sends one time. any idea how to fix it?

**Comment by zelenin** [comment]
$showKeyboard->one_time_keyboard = true;

you should read telegram api docs

**Comment by moein-rahimi** [comment]
yes I used it before but didn't work.
here is my bot repo, i'll be thankful if you mind take a look, line 24 keyboard stuff starts.
https://github.com/moein-rahimi/beheshtinotifier/blob/master/notifier.php

**Comment by zelenin** [comment]
it's not this library issue. read api docs and experiment.

**Comment by moein-rahimi** [comment]
you were damn right ! I used switch instead of if and now it works fine
thank you for your help
