### ISSUE TITLE
cURL error 6: Could not resolve host: api.telegram.org 

### ISSUE THREAD

**Issue by RailG** [zelenin/telegram-bot-api#14]
I creat command /usr/bin/php /application/yii telegram/run
But errror
Exception 'GuzzleHttp\Exception\ConnectException' with message 'cURL error 6: Could not resolve host: api.telegram.org (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)'

in .../application/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:186

**Comment by zelenin** [comment]
It's not library issue.
