### ISSUE TITLE
upgrade telegram-bot-api

### ISSUE THREAD

**Issue by mohammad6006** [zelenin/telegram-bot-api#17]
after update to version 1.0
`$client = new Zelenin\Telegram\Bot\Api($token);
`display this error:
`PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Zelenin\Telegram\Bot\Api::__construct() must be an instance of Zelenin\Telegram\Bot\Client\Client, string given, called in /app/index.php on line 26 and defined in /app/vendor/zelenin/telegram-bot-api/Api.php:26
`
what should I do?

**Comment by zelenin** [comment]
https://github.com/zelenin/telegram-bot-api#usage
