### ISSUE TITLE
leave a group function

### ISSUE THREAD

**Issue by IldeNet** [zelenin/telegram-bot-api#19]
I write in php
$response = $api->leaveChat();
but console says
PHP Fatal error:  Uncaught Error: Call to undefined method Zelenin\Telegram\Bot\Api::leaveChat()

Can you tell me the correct way to use this function?

**Comment by zelenin** [comment]
Do you have this function in Api.php?

**Comment by IldeNet** [comment]
my fault, sorry. i need update Api.php. thanks
