### ISSUE TITLE
How I can use a webhook method?

### ISSUE THREAD

**Issue by nikosid** [zelenin/telegram-bot-api#22]
Hello.
I want to use my bot with webhook method not with getUpdates.
It works very good with your deamon approach.
Also it works with this component and its method https://github.com/unreal4u/telegram-api/wiki/Getting-updates-via-Webhook
I tried do somethimg like this
```
use Zelenin\Telegram\Bot\Type\Update;

$update = new Update($_POST);
```
but it doesn't work.
I got an error:

> TypeError: Argument 1 passed to Zelenin\Telegram\Bot\Type\Type::create() must be an instance of stdClass, array given, called in /var/www/telegram/vendor/zelenin/telegram-bot-api/Type/Update.php on line 60 and defined in /var/www/telegram/vendor/zelenin/telegram-bot-api/Type/Type.php:51

**Comment by zelenin** [comment]
```php
$update = new Update(json_decode($_POST));
```

**Comment by nikosid** [comment]
`Yii\base\ErrorException: json_decode() expects parameter 1 to be string, array given` of course, but this code doesn't work to
```
$body = json_decode(file_get_contents('php://input'));
$update = new Update($body);
```
with that error
`TypeError: Argument 1 passed to Zelenin\Telegram\Bot\Type\Type::__construct() must be of the type array, object given`

**Comment by zelenin** [comment]
maybe ```$body = json_decode(file_get_contents('php://input'), true);``` ?

**Comment by nikosid** [comment]
Yes, I tried and I got this error
`TypeError: Argument 1 passed to Zelenin\Telegram\Bot\Type\Type::create() must be an instance of stdClass, array given`

**Comment by zelenin** [comment]
try this:
```
$response = new \Zelenin\Telegram\Bot\Client\Response(true, json_decode(file_get_contents('php://input')));
$update = Update::createFromResponse($response);
```

**Comment by nikosid** [comment]
It works!
Thank you!
